### ISSUE TITLE
Import "blacksheep" could not be resolved

### ISSUE THREAD

**Issue by zakyyusuff** [Neoteroi/BlackSheep#298] opened 2023-01-05 08:20 UTC
##### _Note: consider using [Discussions](https://github.com/Neoteroi/BlackSheep/discussions) to open a conversation about new features…_

```
from datetime import datetime
from blacksheep import HttpResponse, TextContent
from blacksheep.server import Application


app = Application()

@app.route('/')
async def home(request):
    return HttpResponse(200, content=TextContent(f'Hello, World! {datetime.utcnow().isoformat()}'))

app.start()
```

    **from blacksheep import HttpResponse, TextContent
ModuleNotFoundError: No module named 'blacksheep'**

i already install blacksheep but still not working and no module found how i can solve it? please someon gve me help

**Comment by RobertoPrevato** [comment] 2023-01-05 22:25
Hi @zakyyusuff 
Are you perchance using Vercel? Could this be a duplicate of https://github.com/Neoteroi/BlackSheep/issues/275?

If not, can you please describe your setup, how are you using blacksheep?

**Closed** 2023-01-14 08:08 UTC
