### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by NewDay1313** [Neoteroi/BlackSheep#190] opened 2021-07-26 13:17 UTC
After updating up to v1.0.9:
**File "C:\Users\1\Desktop\Avicena\.\app\templating.py", line 16, in configure_templating
    use_templates(application, PackageLoader(__name__, "views"))
  File "c:\program files\python38\lib\site-packages\jinja2\loaders.py", line 309, in __init__
    raise ValueError(
ValueError: The 'app.templating' package was not installed in a way that PackageLoader understands.**

**Comment by RobertoPrevato** [comment] 2021-07-27 08:03
Hi @NewDay1313, thanks for reporting this bug.

This is related to:
* https://github.com/pallets/jinja/issues/1168 

I will find the solution and add more integration tests to reduce the risk of regressions in Jinja integration in the future. This feature is tested but evidently the current tests don't recreate this scenario.

**Comment by RobertoPrevato** [comment] 2021-07-27 08:05
Note: I can reproduce this bug only when running the application through `uvicorn` (and possibly and ASGI server), not when running the server directly.

**Comment by RobertoPrevato** [comment] 2021-07-27 08:09
@NewDay1313 

to fix, please replace:

```python
use_templates(application, PackageLoader(__name__, "views"))
```

With:

```python
use_templates(application, PackageLoader("app", "views"))
```

Where "app" is the name of the package containing the `views` folder.

I will update the MVC project template to include this fix. Closing now this issue since it's related to how Jinja2 is used and changes in Jinja2 itself.

**Closed by RobertoPrevato** 2021-07-27 08:09 UTC

**Comment by Anonymous1313-tech** [comment] 2021-07-27 09:22
Thanks!
